# Generated by Django 3.2.4 on 2021-07-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('inn', models.CharField(max_length=255, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=255, verbose_name='КПП')),
                ('warehouse_location', models.CharField(max_length=255, verbose_name='Населенный пункт склада')),
            ],
        ),
    ]
