# Generated by Django 3.2.4 on 2021-07-02 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_code', models.CharField(max_length=255, null=True, verbose_name='Код строительного ресурса')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Наименование')),
                ('measure_unit', models.CharField(max_length=255, null=True, verbose_name='Единица измерения')),
                ('last_updated', models.DateField(null=True, verbose_name='Дата последнего обновления')),
                ('page_url', models.URLField(null=True, verbose_name='Ссылка на страницу')),
                ('image_url', models.URLField(null=True, verbose_name='Ссылка на картинку')),
                ('status', models.IntegerField(choices=[(1, 'Неопубликован'), (2, 'Ожидает подтверждения'), (3, 'Опубликован')], db_index=True, verbose_name='статус')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsers.provider', verbose_name='Поставщик')),
            ],
        ),
    ]
