# Generated by Django 3.2.4 on 2021-07-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0003_offerprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerprice',
            name='extraction_date',
            field=models.DateTimeField(null=True, verbose_name='Дата извлечения'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='last_updated',
            field=models.DateTimeField(null=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='offerprice',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, max_length=255, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='offerprice',
            name='price_with_vat',
            field=models.DecimalField(decimal_places=2, max_digits=12, max_length=255, verbose_name='Отпускная цена с НДС'),
        ),
        migrations.AlterField(
            model_name='offerprice',
            name='price_without_vat',
            field=models.DecimalField(decimal_places=2, max_digits=12, max_length=255, verbose_name='Отпускная цена без НДС'),
        ),
    ]
