# Generated by Django 3.2.4 on 2021-07-03 13:11

from django.db import migrations, models
import parsers.models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0006_auto_20210702_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel', models.FileField(upload_to=parsers.models.get_excel_file_path, verbose_name='файл excel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'отчет excel',
                'verbose_name_plural': 'отчеты excel',
                'ordering': ('-created_at',),
            },
        ),
    ]
