# Generated by Django 3.2.4 on 2021-07-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0007_offerprice_screenshot_pdf_url'),
        ('parsers', '0007_product_resource_code'),
    ]

    operations = [
    ]
