# Generated by Django 3.2.4 on 2021-07-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0007_excelreport'),
        ('parsers', '0007_offerprice_screenshot_pdf_url'),
    ]

    operations = [
    ]
