# Generated by Django 3.2.4 on 2021-07-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0008_merge_20210703_2018'),
        ('parsers', '0008_merge_20210703_2049'),
    ]

    operations = [
    ]
